### ISSUE TITLE
Object detection in browser/ Javascript

### ISSUE THREAD

**Issue by malvela** [malvela/BatchProcesses-AutomaticProductFeaturesCollection#12]
https://github.com/hugozanini/TFJS-object-detection
https://javascript.plainenglish.io/face-detection-in-the-browser-using-tensorflow-js-facb2304ed91
https://selvamsubbiah.com/semantic-image-segmentation-in-browser-using-deeplab/

is tensorflow.js what we are looking for?

**Comment by Hannes-G** [comment]
Yep the sources look very helpful, I think it should be possible to visualize the detected grains in the images with them

**Comment by Hannes-G** [comment]
Moved to Flour
