### ISSUE TITLE
Angebot Steckernetzteil

### ISSUE THREAD

**Issue by malvela** [malvela/BatchProcesses-AutomaticProductFeaturesCollection#7]

**Comment by Hannes-G** [comment]
https://www.reichelt.com/de/en/usb-dc-power-plug-5-5-2-1-5-v-length-1-0-m-delock-82197-p130988.html?&nbc=1&trstct=lsbght_sldr::224213

**Comment by malvela** [comment]
wäre nicht besser mit Netzteil?

**Comment by Hannes-G** [comment]
Vielleicht hast du recht, ich hatte die erst auf reicheltelectronics nicht gefunden...

https://www.reichelt.com/de/en/plug-in-switching-adaptor-12-w-5-v-2-4-a-hnp-12-050l6-p177057.html?&trstct=pol_3&nbc=1

**Comment by malvela** [comment]
in Bearbeitung...
